django_app/api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path("",views.index,name="index"),
    path("plast",views.plast,name="plast"),
    path("msgs",views.msgs,name="msgs"),
    path("usr",views.usr,name="usr"),
    path("usr/<int:usr_id>",views.usr,name="usr"),
    path("post",views.post,name="post"),
    path("good/<int:good_id>",views.good,name="good"),
]

django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('hello.urls')),
    path('sns/',include('sns.urls')),
    path('api/',include('api.urls')),
]

django_app/hello/urls.py
from django.urls import path
from . import views
from hello.views import HelloView

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:num>',views.index,name='index'),
    path('next',views.next,name='next'),
    path('form',views.form,name='form'),
    path('index2',HelloView.as_view(),name='index2'),
    path('formSample',views.sample,name='formSample'),
    path('sessionSample',views.sessionSample,name='sessionSample'),
    path('create',views.create,name='create'),
    path('edit/<int:num>',views.edit,name='edit'),
    path('delete/<int:num>',views.delete,name='delete'),
    path('detail/<int:num>',views.detail,name='detail'),
    path('find',views.find, name='find'),
    path('check',views.check, name='check'),
    path('message/',views.message, name='message'),
    path('message/<int:page>',views.message, name='message'),
]

django_app/hello/models.py
from django.db import models
from django.core.validators import ValidationError
from django.core.validators import MinLengthValidator
from django.core.validators import URLValidator
from django.core.validators import RegexValidator
import re

# Create your models here.
# 数字のバリデーター関数
def number_only(value):
    if (re.match(r"^[0-9]*$",value) == None):
        raise ValidationError(
            "%(value)s is not Number!",
            params = {"value": value}
        )

class Friend(models.Model):
    # name = models.CharField(max_length=100,validators=[
    #     MinLengthValidator(10),      # Ensure this value has at least 10 characters (it has 8).
    #     URLValidator(),              # Enter a valid URL.
    #     RegexValidator(r'^[a-z]*$'), # Enter a valid value.
    #     number_only                  # aaaa is not Number!
    #     ])
    name = models.CharField(max_length=100)
    mail = models.EmailField(max_length=100)
    gender = models.BooleanField()
    age = models.IntegerField(default=0)
    birthday = models.DateField()

    def __str__(self):
        return "<Friend:id=" + str(self.id) + "," + self.name + "(" + str(self.age) + ")>" 


# メッセージモデル
class Message(models.Model):
    friend = models.ForeignKey(Friend, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "<Message:id> = " + str(self.id) + "," + self.title + "(" + str(self.pub_date) + ")>"
    
    class Meta:
        ordering = ("pub_date",)

django_app/hello/forms.py
from django import forms
from .models import Friend
from .models import Message

# MessageForm
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ["title","content","friend"]
        widgets = {
            "title":forms.TextInput(attrs={"class":"form-control form-control-sm"}),
            "content":forms.Textarea(attrs={"class":"form-control form-control-sm"}),
            "friend":forms.Select(attrs={"class":"form-control form-control-sm"}),
        }
        labels = {
            "title":"タイトル",
            "content":"メッセージ",
            "friend":"投稿者",
        }

# checkフォーム
class CheckForm(forms.Form):
    str = forms.CharField(label="文字列",required=True)
    def clean(self):
        cleaned_data = super().clean()
        str = cleaned_data["str"]
        if (str.lower().startswith("no")):
            raise forms.ValidationError("「no」で始まる入力がありました。")

    min = forms.CharField(label="最小入力数",min_length=3) # 最小文字数:3
    max = forms.CharField(label="最大入力数",max_length=5) # 最大文字数:5
    num = forms.IntegerField(label="数値",min_value=10,max_value=50) # 最小値:10,最大値:50
    date = forms.DateField(label="日付",input_formats=["%d"]) # 1～31までの日
    time = forms.TimeField(label="時間") # 時間 17:00
    datatime = forms.DateTimeField(label="日時",input_formats=["Y/m/d H:i"])

# Findフォーム
class FindForm(forms.Form):
    find = forms.CharField(label='Find',required=False,widget=forms.TextInput(attrs={'style':'width:400px;'}))

# モデルフォーム
class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name','mail','gender','age','birthday']
        widgets = {
            "name":forms.TextInput(attrs={"class":"form-control"}),
            "mail":forms.EmailInput(attrs={"class":"form-control"}),
            "age":forms.NumberInput(attrs={"class":"form-control"}),
            "birthday":forms.DateInput(attrs={"class":"form-control"}),
        }


# 登録フォーム
class RegisterForm(forms.Form):
    name = forms.CharField(label='名前',widget=forms.TextInput(attrs={'class':'form-control'}))
    mail = forms.EmailField(label='メールアドレス',widget=forms.EmailInput(attrs={'class':'form-control'}))
    gender = forms.BooleanField(label='性別',required=False,widget=forms.CheckboxInput(attrs={'class':'form-check'}))
    age = forms.IntegerField(label='年齢',widget=forms.NumberInput(attrs={'class':'form-control'}))
    birthday = forms.DateField(label='生年月日',widget=forms.DateInput(attrs={'class':'form-control'}))

# SearchForm ID検索フォーム
class SearchForm(forms.Form):
    id = forms.IntegerField(label='ID検索',widget=forms.TextInput(attrs={'class':'form-control'}))

# HelloForm
class HelloForm(forms.Form):
    name = forms.CharField(label="名前",required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    mail = forms.URLField(label="メールアドレス",required=True,widget=forms.TextInput(attrs={'class':'form-control'}))
    age = forms.IntegerField(label="年齢",required=True,widget=forms.NumberInput(attrs={'class':'form-control'}))

# サンプルフォーム
class SampleForm(forms.Form):
    # input type="text"
    text = forms.CharField(label="テキスト")

    # input type="email"
    mail = forms.EmailField(label="メールアドレス")

    # input type="number"
    number = forms.IntegerField(label="ナンバー")

    # input type="number" step="0.1"
    number_float = forms.FloatField(label="浮動小数")

    # input type="url"
    url = forms.URLField(label="URL")

    # input type="date" 例) 2024-06-19 2024/06/19
    date = forms.DateField(label="日付")

    # input type="time"  例) 15:30:40
    time = forms.TimeField(label="時刻")

    # input type="datetime-local" 例) 2024-06-19 15:30:40
    dateTime = forms.DateTimeField(label="日時")

    # input type="checkbox"
    check = forms.BooleanField(label="チェックボックス",required=False)

    # select
    data = [("A","item1"),("B","item2"),("C","item3")]
    select = forms.ChoiceField(label="セレクト",choices=data,widget=forms.Select())

    # input type="radio"
    radio = forms.ChoiceField(label="ラジオ",choices=data,widget=forms.RadioSelect())

    # input type="chechbox" 複数選択
    checkbox = forms.MultipleChoiceField(label="複数選択",choices=data,widget=forms.SelectMultiple())


class SessionForm(forms.Form):
    session = forms.CharField(label="セッション")

django_app/hello/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .forms import HelloForm
from .forms import SampleForm
from .forms import SessionForm
from .forms import SearchForm
from .forms import RegisterForm
from .forms import FriendForm
from .forms import MessageForm
from .forms import FindForm
from .forms import CheckForm

from django.views.generic import TemplateView
from .models import Friend
from .models import Message
from django.db.models import Q
from django.db.models import Count,Sum,Avg,Min,Max

# ページネーション
from django.core.paginator import Paginator

# メッセージ関数
def message(request, page=1):
    if (request.method=="POST"):
        obj = Message()
        form = MessageForm(request.POST,instance=obj)
        form.save()

    data = Message.objects.all().reverse()
    paginator = Paginator(data,5)
    params = {
        "title":"Message",
        "form":MessageForm(),
        "data":paginator.get_page(page),
    }

    return render(request, "hello/message.html",params)


def check(request):
    params = {
        "title":"Hello Check",
        "message":"チェック バリデーション",
        "form":FriendForm()
    }

    if (request.method == "POST"):

        obj = Friend()
        form = FriendForm(request.POST,instance=obj)
        params["form"] = form

        if (form.is_valid()):
            params["msg"] = "OK!"
        else:
            params["msg"] = "no good!"

    return render(request,"hello/check.html",params)


## check
# def check(request):
#     params = {
#         "title":"Hello Check",
#         "message":"チェック バリデーション",
#         "form":CheckForm()
#     }

#     if (request.method == "POST"):
#         form = CheckForm(request.POST)
#         params["form"] = form

#         if (form.is_valid()):
#             params["msg"] = "OK!"
#         else:
#             params["msg"] = "no good!"

#     return render(request,"hello/check.html",params)


## find
def find(request):

    if (request.method == 'POST'):
        form = FindForm(request.POST)
        find = request.POST['find'] # リクエストパラメータの取得
        # value = find.split() # ["10","20"]

        ### 文字列検索
        # data = Friend.objects.filter(name=find) # 名前検索
        # data = Friend.objects.filter(name__contains=find) # あいまい検索
        # data = Friend.objects.filter(name__icontains=find) # 大文字小文字区別なし
        # data = Friend.objects.filter(name__istartswith=find) # 先頭検索
        # data = Friend.objects.filter(name__iendswith=find) # 末尾検索
        # data = Friend.objects.filter(name__iexact=find) # 完全一致検索 大文字小文字区別なし
        ### 数値検索
        # data = Friend.objects.filter(age=int(find)) # 年齢検索
        # data = Friend.objects.filter(age__gt=int(find)) # より大きい
        # data = Friend.objects.filter(age__gte=int(find)) # 以上
        # data = Friend.objects.filter(age__lt=int(find)) # より小さい
        # data = Friend.objects.filter(age__lte=int(find)) # 以下
        ### 複数条件
        # data = Friend.objects.filter(age__gte=int(value[0]),age__lte=int(value[1])) # ~以上~以下 
        # data = Friend.objects.filter(Q(name__contains=find) | Q(mail__contains=find)) # 2件以上の検索
        # data = Friend.objects.all()[int(value[0]):int(value[1])]
        # msg = 'Result:' + str(data.count())

        # data = Friend.objects.all()

        sql = "select * from hello_friend"

        if (find != ""):
            sql += " where " + find

        data = Friend.objects.raw(sql)

        re1 = Friend.objects.aggregate(Count("age"))
        re2 = Friend.objects.aggregate(Sum("age"))
        re3 = Friend.objects.aggregate(Avg("age"))
        re4 = Friend.objects.aggregate(Min("age"))
        re5 = Friend.objects.aggregate(Max("age"))

        print(re1,re2,re3,re4,re5) 
        ### {'age__count': 5} {'age__sum': 111} {'age__avg': 22.2} {'age__min': 7} {'age__max': 39}


        msg = "Count:" + str(re1["age__count"]) + "<br>"\
            + "Sum:" + str(re2["age__sum"]) + "<br>"\
            + "Avg:" + str(re3["age__avg"]) + "<br>"\
            + "Min:" + str(re4["age__min"]) + "<br>"\
            + "Max:" + str(re5["age__max"])
 
    else:
        msg = "検索ワード"
        form = FindForm()
        data = Friend.objects.all().order_by("age").reverse()

    params = {
        'title' : "Hello",
        'message' : msg,
        'form' : form,
        'data' : data,
    }

    return render(request, 'hello/find.html', params)

## detail
def detail(request,num):
    obj = Friend.objects.get(id=num) # id指定でデータを取得
    params = {
        'title':"Hello",
        'message':"詳細",
        'id':num,
        'obj':obj
    }
    return render(request,'hello/detail.html',params)

## delete
def delete(request,num):
    obj = Friend.objects.get(id=num) # id指定でデータを取得

    if(request.method=='POST'):
        obj.delete()

        return redirect(to='/hello') # リダイレクト

    params = {
        'title':"Hello",
        'message':"削除",
        'id':num,
        'obj':obj
    }
    return render(request,'hello/delete.html',params)

## edit
def edit(request,num):
    obj = Friend.objects.get(id=num) # id指定でデータを取得

    # postリクエストされた場合
    if(request.method=='POST'):

        # 登録処理と同じ
        friend = FriendForm(request.POST,instance=obj)
        friend.save()

        return redirect(to='/hello') # リダイレクト

    params = {
        'title':"Hello",
        'message':"更新",
        'id':num,
        'form':FriendForm(instance=obj), # 取得したオブジェクトをフォームに入れる
    }
    return render(request,'hello/edit.html',params)

## create
def create(request):
    params = {
        'title':"Hello",
        'message':"登録",
        'form':FriendForm(),
    }

    if(request.method=='POST'):
        obj = Friend()
        # name = request.POST['name']
        # mail = request.POST['mail']
        # gender = 'gender' in request.POST
        # age = int(request.POST['age'])
        # birthday = request.POST['birthday']
        # firend = Friend(name=name,mail=mail,gender=gender,age=age,birthday=birthday)
        friend = FriendForm(request.POST,instance=obj)
        friend.save()

        # 保存が出来たらindexへリダイレクト
        return redirect(to='/hello')

    return render(request,'hello/create.html', params)

## index
def index(request,num=1):

    data = Friend.objects.all()
    page = Paginator(data,3)

    params = {
        'title':"Hello",
        'message':"Friend一覧",
        'form':SearchForm(),
        'data':page.get_page(num)
    }

    if (request.method=='POST'):
        params['form'] = SearchForm(request.POST) # 検索フォーム

        num = request.POST['id']    # リクエストパラメータの取得
        try:
            item = Friend.objects.get(id=num)  # クエリセットの取得
            params['data'] = [item]
        except:
            params['msg'] = "データが見つかりませんでした。"
            params['data'] = Friend.objects.all().values('id','name')
    
    return render(request,'hello/index.html',params)



# def index(request):

#     params = {
#         'title':"Hello",
#         'message':"Friend一覧",
#         'form':SearchForm(),
#         'data':[]
#     }

#     if (request.method=='POST'):
#         params['form'] = SearchForm(request.POST) # 検索フォーム

#         num = request.POST['id']    # リクエストパラメータの取得
#         try:
#             item = Friend.objects.get(id=num)  # クエリセットの取得
#             params['data'] = [item]
#         except:
#             params['msg'] = "データが見つかりませんでした。"
#             params['data'] = Friend.objects.all().values('id','name')
            
#     else:
#         params['data'] = Friend.objects.all().values()
       
#     return render(request,'hello/index.html',params)


## セッション
def sessionSample(request):
    params = {
        'msg':"",
        'form':SessionForm(),
    }

    if request.method=="GET":
        msg = request.session.get("Last_msg","No message")
        params['msg'] = msg

    if request.method=="POST":
        ses = request.POST['session']
        
        request.session['Last_msg'] = ses
        params['msg'] = "send:" + ses

    return render(request,'hello/sessionSample.html',params)

def sample(request):
    params = {
        'msg':"",
        'form':SampleForm(),
    }

    if(request.method=='POST'):
        text = request.POST['text']
        mail = request.POST['mail']
        number = request.POST['number']
        number_float = request.POST['number_float']
        url = request.POST['url']
        date = request.POST['date']
        time = request.POST['time']
        dateTime = request.POST['dateTime']

        # チェックボックス
        if ('check' in request.POST):
            check = "Checked"
        else:
            check = "none Checked"

        select = request.POST['select']
        radio = request.POST['radio']

        # 複数選択はリストで取得
        check_list = request.POST.getlist('checkbox')


        msg= (text,mail,number,number_float,url,date,time,dateTime,check,select,radio,check_list)
        params['msg'] = msg
    return render(request,'hello/formSample.html',params)

class HelloView(TemplateView):

    # 初期化
    def __init__(self):
        self.params = {
            'title':"Hello/Index2",
            'message':"あなたのデータ:",
            'form':HelloForm(),
        }

    # GET送信されて来た場合のメソッド
    def get(self,request):
        return render(request,"hello/index2.html",self.params)

    # POST送信されて来た場合のメソッド
    def post(self,request):
        name = request.POST['name']
        mail = request.POST['mail']
        age = request.POST['age']

        msg = "あなたは、"+ name + "(" + age + ")です。<br>メールアドレスは" + mail + "ですね。" 

        self.params['message'] = msg
        self.params['form'] = HelloForm()

        return render(request,'hello/index2.html',self.params)

# indexのページ
# def index(request):

#     params = {
#         'title':"Hello/index",
#         'msg':"あなたのデータを入力",
#         'form': HelloForm()
#     }

#     # リクエストパラメータがあった場合
#     if (request.method == 'POST'):

#         # リクエストパラメータの取得
#         name = request.POST['name']
#         mail = request.POST['mail']
#         age = request.POST['age']
        

django_app/hello/templates/hello/check.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>バリデーション サンプル</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>

<body class="container">
    <p>{{ message |safe }}:{{ msg }}</p>

    {% for item in form %}
    <p>{{ item.name }}:{{ item.errors }}</p>
    {% endfor %}

    <form action="{% url 'check' %}" method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Click">
    </form>
</body>

</html>

django_app/hello/templates/hello/create.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'hello/css/style.css' %}" type="text/css">
</head>
<body class="container">
    <h1 class="display-3 text-danger">{{ title }}</h1>
    <p class="h5 mt-4">{{ message|safe }}</p>

    <form action="{% url 'create' %}" method="post">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
            <tr>
                <th></th>
                <td>
                    <input type="submit" value="送信" class="btn btn-primary mt-2">
                    <input type="reset" value="リセット" class="btn btn-primary mt-2">
                    <a href="{% url 'index' %}" class="btn btn-primary mt-2">戻る</a>
                </td>
            </tr>
        </table>
    </form>

</body>
</html>

django_app/hello/templates/hello/delete.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'hello/css/style.css' %}" type="text/css">
</head>
<body class="container">
    <h1 class="display-3 text-danger">{{ title }}</h1>
    <p class="h5 mt-4">{{ message|safe }}</p>
    <table class="table">
        <tr>
            <th>ID</th>
            <td>{{ obj.id }}</td>
        </tr>
        <tr>
            <th>名前</th>
            <td>{{ obj.name }}</td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td>{{ obj.mail }}</td>
        </tr>
        <tr>
            <th>性別</th>
            <td>
                {% if obj.gender == False %}female{% endif %}
                {% if obj.gender == True %}male{% endif %}
            </td>
        </tr>
        <tr>
            <th>年齢</th>
            <td>{{ obj.age }}</td>
        </tr>
        <tr>
            <th>生年月日</th>
            <td>{{ obj.birthday }}</td>
        </tr>
        <form action="{% url 'delete' id %}" method="post">
            {% csrf_token %}
            <tr>
                <th></th>
                <td>
                    <input type="submit" value="削除" class="btn btn-primary mt-2">
                    <a href="{% url 'index' %}" class="btn btn-primary mt-2">戻る</a>
                </td>
            </tr>
        </form>
    </table>

</body>
</html>

django_app/hello/templates/hello/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'hello/css/style.css' %}" type="text/css">
</head>
<body class="container">
    <h1 class="display-3 text-danger">{{ title }}</h1>
    <p class="h5 mt-4">{{ message|safe }}</p>
    <table class="table">
        <tr>
            <th>ID</th>
            <td>{{ obj.id }}</td>
        </tr>
        <tr>
            <th>名前</th>
            <td>{{ obj.name }}</td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td>{{ obj.mail }}</td>
        </tr>
        <tr>
            <th>性別</th>
            <td>
                {% if obj.gender == False %}female{% endif %}
                {% if obj.gender == True %}male{% endif %}
            </td>
        </tr>
        <tr>
            <th>年齢</th>
            <td>{{ obj.age }}</td>
        </tr>
        <tr>
            <th>生年月日</th>
            <td>{{ obj.birthday }}</td>
        </tr>
        <tr>
            <th></th>
            <td>
                <a href="{% url 'index' %}" class="btn btn-primary mt-2">戻る</a>
            </td>
        </tr>
    </table>
</body>
</html>

django_app/hello/templates/hello/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'hello/css/style.css' %}" type="text/css">
</head>
<body class="container">
    <h1 class="display-3 text-danger">{{ title }}</h1>
    <p class="h5 mt-4">{{ message|safe }}</p>

    <form action="{% url 'edit' id %}" method="post">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
            <tr>
                <th></th>
                <td>
                    <input type="submit" value="更新" class="btn btn-primary mt-2">
                    <input type="reset" value="リセット" class="btn btn-primary mt-2">
                    <a href="{% url 'index' %}" class="btn btn-primary mt-2">戻る</a>
                </td>
            </tr>
        </table>
    </form>

</body>
</html>

django_app/hello/templates/hello/formSample.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>form サンプル</title>
</head>
<body class="container">
    <p>{{ msg }}</p>
    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Click">
    </form>
</body>
</html>

django_app/hello/templates/hello/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'hello/css/style.css' %}" type="text/css">
</head>

<body class="container">
    <h1 class="display-3 text-danger">{{ title }}</h1>
    <p class="h5 mt-4">{{ message|safe }}</p>

    <!-- <p>{{ data }}</p> -->


    <!-- 検索フォーム -->
    <form action="{% url 'index' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="検索" class="btn btn-primary mt-2">
    </form>

    <P><a href="{% url 'create' %}" class="btn btn-primary mt-2">新規登録</a></P>
    <p>{{ msg }}</p>

    <!-- 一覧テーブル -->
    <table class="table">
        <tr>
            <th>ID</th>
            <th>name</th>
            <th>gender</th>
            <th>mail</th>
            <th>age</th>
            <th>birthday</th>
            <th>message</th>
            <th></th>
            <th></th>
        </tr>
        {% for item in data %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.name }}</td>
            <td>
                {% if item.gender == True %}male{% endif %}
                {% if item.gender == False %}female{% endif %}
            </td>
            <td>{{ item.mail }}</td>
            <td>{{ item.age }}</td>
            <td>{{ item.birthday }}</td>
            <td>
                <ul>
                    {% for ob in item.message_set.all %}
                    <li>{{ ob.title }}</li>
                    {% endfor %}
                </ul>
            </td>

            <td><a href="{% url 'detail' item.id %}">詳細</a></td>
            <td><a href="{% url 'edit' item.id %}">更新</a></td>
            <td><a href="{% url 'delete' item.id %}">削除</a></td>

        </tr>
        {% endfor %}
    </table>

    <!-- ページャー -->
    <ul class="pagination">
        <!-- 前に行く処理 -->
        {% if data.has_previous %}
        <li class="page-item">
            <a href="{% url 'index' %}" class="page-link">＜＜最初</a>
        </li>
        <li class="page-item">
            <a href="{% url 'index' %}{{data.previous_page_number}}" class="page-link">＜前</a>
        </li>
        {% else %}
        <!-- 1ページ目 -->
        <li class="page-item">
            <a href="" class="page-link">＜＜最初</a>
        </li>
        <li class="page-item">
            <a href="" class="page-link">＜前</a>
        </li>
        {% endif %}
        <!-- ページ番号の表示 -->
        <li class="page-item">
            <a class="page-link">{{data.number}}/{{data.paginator.num_pages}}</a>
        </li>

        <!-- 後ろに行く処理 -->
        {% if data.has_next %}
        <li class="page-item">
            <a href="{% url 'index' %}{{ data.next_page_number }}" class="page-link">次＞</a>
        </li>
        <li class="page-item">
            <a href="{% url 'index' %}{{data.paginator.num_pages}}" class="page-link">最後＞＞</a>
        </li>
        {% else %}
        <!-- 最後のページの場合 -->
        <li class="page-item">
            <a href="" class="page-link">次＞</a>
        </li>
        <li class="page-item">
            <a href="" class="page-link">最後＞＞</a>
        </li>
        {% endif %}
    </ul>

</body>

</html>

django_app/hello/templates/hello/sessionSample.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session サンプル</title>
</head>
<body class="container">
    <p>{{ msg }}</p>
    <form action="{% url 'sessionSample' %}" method="post">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Click">
    </form>
</body>
</html>